// storage/framework/defaults/components/Marketing/Layout.vue
<script setup lang="ts">
// into useHead
// const metadata = {
//   title: {
//     template: '%s - TaxPal',
//     default: 'TaxPal - Accounting made simple for small businesses',
//   },
//   description: 'Most bookkeeping software is accurate, but hard to use. We make the opposite trade-off, and hope you don’t get audited.',
// }

const inter = {
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-inter',
}

const lexend = {
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-lexend',
}
</script>

<template>
  <html
    lang="en"
    class="h-full scroll-smooth bg-white antialiased" :class="[
      inter.variable,
      lexend.variable,
    ]"
  >
    <body class="h-full flex flex-col">
      <slot />
    </body>
  </html>
</template>

// resources/types/salient/app/layout.tsx
import { Inter, Lexend } from 'next/font/google'
import clsx from 'clsx'

import '@/styles/tailwind.css'
import { type Metadata } from 'next'

export const metadata: Metadata = {
  title: {
    template: '%s - TaxPal',
    default: 'TaxPal - Accounting made simple for small businesses',
  },
  description:
    'Most bookkeeping software is accurate, but hard to use. We make the opposite trade-off, and hope you don’t get audited.',
}

const inter = Inter({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-inter',
})

const lexend = Lexend({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-lexend',
})

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html
      lang="en"
      className={clsx(
        'h-full scroll-smooth bg-white antialiased',
        inter.variable,
        lexend.variable,
      )}
    >
      <body className="flex h-full flex-col">{children}</body>
    </html>
  )
}
